### ISSUE TITLE
Make available on NPM

### ISSUE THREAD

**Issue by reinink** [openbibleinfo/Bible-Reference-Converter#1]
It would be great if this library was available on NPM, just like the "Bible-Passage-Reference-Parser" library. I'm using "Bible-Passage-Reference-Parser" to parse bible texts from strings, and then using this library to format them. However, it's a bit of a challenge including it in my project with no NPM support.

Thanks for these awesome projects!

**Comment by jerodfritz** [comment]
+1

**Comment by cco3** [comment]
Looks like @reinink went ahead and made a packaged version:
https://github.com/reinink/Bible-Reference-Formatter

@reinink, how are you using this? (is it on npm somewhere?)  Want to try making a PR?

**Comment by reinink** [comment]
So, I think I forked it simply to ensure the library didn't disappear. I think it also made it easier to install this way:

```js
"bible-reference-formatter": "git://github.com/reinink/Bible-Reference-Formatter.git",
```

Since, I think you need to have a `package.json` file in order for this to work.

Meaning...I don't think I ever actually published it to NPM, but that would honestly be great, and I would be happy to do this from my fork if that's what it takes. Feel free to submit a PR. 👍 

To be honest, I secretly keep hoping that Stephen Smith (who I believe is behind these very helpful libraries) will eventually jump back into this project and continue maintaining them. It's been four years though. 😕 

Stephen...if you are listening, would it be possible to add myself as a maintainer on the openbibleinfo GitHub org, so I can help maintain these libraries?

**Comment by openbibleinfo** [comment]
Hi, I’m happy to add it to NPM. I just don’t have any experience adding a package with a dependency, so I’m not sure of the syntax In package.json. If you’d like to submit a PR, I can merge it and push it to NPM.

**Comment by reinink** [comment]
@openbibleinfo Amazing! We'll get you a PR. 👍

@cco3 Do you want to take care of this, or do you want me to?

**Comment by cco3** [comment]
Here: #2

**Comment by cco3** [comment]
@openbibleinfo OK, I also just went ahead and published it since this is a low activity repository and wanted to save you the hassle if you'd rather not get set up with npm to publish.  If you do want to, create an account on npm; I can add you as an owner (and you can remove me as one if you want).

https://www.npmjs.com/package/bible-reference-formatter

**Comment by cco3** [comment]
Also, I just packaged it up as is without providing support for complie-and-run.sh.  If we want to make sure that can build after a simple "npm install", I figure that can be done as a second step.

Essentially you just do `npm install --save-dev <packagename>` with each dependency and they will appear in the package.json file and package-lock.json files as needed.

**Comment by reinink** [comment]
Thanks for your work on this @cco3. Now I can delete my fork. 👌
